name: Build Ra_Reader Windows x64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows-x64:
    runs-on: windows-latest

    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller pillow

      - name: Build EXE
        run: >
          pyinstaller
          --noconfirm
          --clean
          --onefile
          --windowed
          --name "Ra_Reader"
          --icon "icon.ico"
          --add-data "Alice-Regular.ttf;."
          Ra_Reader.pyw

      - name: Upload Windows x64 build
        uses: actions/upload-artifact@v4
        with:
          name: Ra_Reader-Windows-x64
          path: dist/Ra_Reader.exe
